astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 3

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.5-flash-lite"
    temperature: 0
    max_output_tokens: 2048

  openai:
     provider: "openai"
     model_name: "gpt-4o"
     temperature: 0
